/*
===============================================================================
 Azure Landing Zone Lab - Scenario 5
 Management Groups + Policy + Management Resources Only

 Lab design:
 - Single Azure subscription
 - Central India
 - No connectivity platform
 - No Azure Firewall / vWAN / NVA
 - No subscription vending
 - Management subscription placement only
 - Log Analytics / management foundation retained
 - Broad Defender for Cloud auto-enablement disabled for cost control
===============================================================================
*/


/*
--- Starter Locations ---
Primary Azure region for the platform resources.
*/
starter_locations = ["centralindia"]


/*
--- Custom Replacements ---
*/
custom_replacements = {

  /*
  --- Custom Name Replacements ---
  */
  names = {

    # Defender email is not being actively used in this lab because
    # automatic Defender policy deployment is disabled below.
    defender_email_security_contact = "messagefromgiri@live.com"

    # Resource group names
    management_resource_group_name            = "rg-management-$${starter_location_01}"
    asc_export_resource_group_name            = "rg-asc-export-$${starter_location_01}"
    service_health_alerts_resource_group_name = "rg-service-health-alerts-$${starter_location_01}"

    # Resource names
    log_analytics_workspace_name            = "law-management-$${starter_location_01}"
    ama_user_assigned_managed_identity_name = "uami-management-ama-$${starter_location_01}"
    dcr_change_tracking_name                = "dcr-change-tracking"
    dcr_defender_sql_name                   = "dcr-defender-sql"
    dcr_vm_insights_name                    = "dcr-vm-insights"
  }


  /*
  --- Custom Resource Group Identifier Replacements ---
  */
  resource_group_identifiers = {

    management_resource_group_id = "/subscriptions/$${subscription_id_management}/resourcegroups/$${management_resource_group_name}"
  }


  /*
  --- Custom Resource Identifier Replacements ---
  */
  resource_identifiers = {

    ama_change_tracking_data_collection_rule_id = "$${management_resource_group_id}/providers/Microsoft.Insights/dataCollectionRules/$${dcr_change_tracking_name}"

    ama_mdfc_sql_data_collection_rule_id = "$${management_resource_group_id}/providers/Microsoft.Insights/dataCollectionRules/$${dcr_defender_sql_name}"

    ama_vm_insights_data_collection_rule_id = "$${management_resource_group_id}/providers/Microsoft.Insights/dataCollectionRules/$${dcr_vm_insights_name}"

    ama_user_assigned_managed_identity_id = "$${management_resource_group_id}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$${ama_user_assigned_managed_identity_name}"

    log_analytics_workspace_id = "$${management_resource_group_id}/providers/Microsoft.OperationalInsights/workspaces/$${log_analytics_workspace_name}"
  }
}


/*
--- Tags ---
*/
tags = {
  deployed_by = "terraform"
  source      = "Azure Landing Zones Accelerator"
  environment = "lab"
  course_module = "module6"
}


/*
===============================================================================
 MANAGEMENT RESOURCES
===============================================================================
*/

management_resources_enabled = true

management_resource_settings = {

  location                     = "$${starter_location_01}"
  log_analytics_workspace_name = "$${log_analytics_workspace_name}"
  resource_group_name          = "$${management_resource_group_name}"

  user_assigned_managed_identities = {

    ama = {
      name = "$${ama_user_assigned_managed_identity_name}"
    }
  }

  data_collection_rules = {

    change_tracking = {
      name = "$${dcr_change_tracking_name}"
    }

    defender_sql = {
      name = "$${dcr_defender_sql_name}"
    }

    vm_insights = {
      name = "$${dcr_vm_insights_name}"
    }
  }
}


/*
===============================================================================
 MANAGEMENT GROUPS + POLICY
===============================================================================
*/

management_groups_enabled = true

management_group_settings = {

  /*
  Use the architecture generated by the Accelerator:
  config/lib/architecture_definitions/alz_custom.alz_architecture_definition.yaml
  */
  architecture_name = "alz_custom"

  location = "$${starter_location_01}"

  /*
  inputs.yaml has:
      root_parent_management_group_id: ""

  Therefore the ALZ hierarchy is created beneath Tenant Root Group.
  */
  parent_resource_id = "$${root_parent_management_group_id}"


  /*
  Values consumed by ALZ policy definitions.
  */
  policy_default_values = {

    ama_change_tracking_data_collection_rule_id = "$${ama_change_tracking_data_collection_rule_id}"

    ama_mdfc_sql_data_collection_rule_id = "$${ama_mdfc_sql_data_collection_rule_id}"

    ama_vm_insights_data_collection_rule_id = "$${ama_vm_insights_data_collection_rule_id}"

    ama_user_assigned_managed_identity_id = "$${ama_user_assigned_managed_identity_id}"

    ama_user_assigned_managed_identity_name = "$${ama_user_assigned_managed_identity_name}"

    log_analytics_workspace_id = "$${log_analytics_workspace_id}"

    resource_group_name_service_health_alerts = "$${service_health_alerts_resource_group_name}"

    resource_group_name_mdfc = "$${asc_export_resource_group_name}"

    resource_group_location = "$${starter_location_01}"

    email_security_contact = "$${defender_email_security_contact}"
  }


  /*
  ===========================================================================
  SINGLE SUBSCRIPTION PLACEMENT
  ===========================================================================

  Our one Azure subscription is placed only in the Management MG.

  We deliberately DO NOT place subscriptions into:
      identity
      connectivity
      security
  */
  subscription_placement = {

    management = {
      subscription_id       = "$${subscription_id_management}"
      management_group_name = "management"
    }
  }


  /*
  ===========================================================================
  POLICY CUSTOMIZATION
  ===========================================================================
  */
  policy_assignments_to_modify = {

    /*
    Disable automatic Microsoft Defender for Cloud enablement for this
    cost-controlled learning lab.

    We can enable selected Defender plans later intentionally.
    */
    alz = {

      policy_assignments = {

        Deploy-MDFC-Config-H224 = {
          creation_enabled = false
        }
      }
    }


    /*
    No DDoS Network Protection deployment.
    */
    connectivity = {

      policy_assignments = {

        Enable-DDoS-VNET = {
          creation_enabled = false
        }
      }
    }


    /*
    No DDoS plan for workload landing zones.
    */
    landingzones = {

      policy_assignments = {

        Enable-DDoS-VNET = {
          creation_enabled = false
        }
      }
    }


    /*
    No enterprise-scale Private DNS zone deployment for this lab.
    */
    corp = {

      policy_assignments = {

        Deploy-Private-DNS-Zones = {
          creation_enabled = false
        }
      }
    }
  }
}


/*
===============================================================================
 CONNECTIVITY
===============================================================================

Scenario 5 deliberately does not deploy a platform connectivity architecture.
Our application VNets will be added separately later.
*/

connectivity_type = "none"


/*
===============================================================================
 TELEMETRY
===============================================================================
*/

enable_telemetry = true

telemetry_additional_content = {
  deployed_by    = "alz-terraform-accelerator"
  correlation_id = "00000000-0000-0000-0000-000000000000"
}
